In [2]:
#1.creation of array

import numpy as np

a = np.array([1, 2, 3, 4, 5])
b=((1,2,3,4))

print(a)

print(b)

[1 2 3 4 5]
(1, 2, 3, 4)


In [3]:
#2. 2-D ARRAY


a = np.array([[1, 2, 3], [4, 5, 6]])

print(a)

[[1 2 3]
 [4 5 6]]


In [4]:
#3.check the number dimension

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [ ]:
#4.